### ISSUE TITLE
Reported as unsafe?

### ISSUE THREAD

**Issue by cd-FileX** [ltheinrich/etopa#191]
If I try to install the app, google blocks me from doing so, saying the app could do bad stuff with my system, which has not yet been happening for other apps.

**Comment by ltheinrich** [comment]
Hi, are you trying to install the app from Google Play or are you using the APK from GitHub? If it is the APK, then I think it shows a warning, because Google Play signs the app bundle with a different key/signature than the APK on GitHub.

Anyway, if you downloaded the app from here or from Google Play, the app will NOT do anything bad to your system.

Could you provide a screenshot of that warning?

**Comment by ltheinrich** [comment]
Unfortunately, it seems like I can't do anything to prevent the warning when downloading the app from anywhere else than Google Play Store (because of Play App Signing). But is should only appear on the first installation.

I should have disabled Play App Signing when I published the app on Google Play Store...

**Comment by ltheinrich** [comment]
Thank you for your report, but since I think that it is not possible to prevent this warning because of Play App Signing (only installing it from Google Play will prevent the warning), I am closing the issue. If you know to fix it or want to report another problem, feel free to open a new issue :)
