### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by er2de2** [ltheinrich/etopa#196]
Hello.
New version of docker image planned?

**Comment by ltheinrich** [comment]
Hi, I have updated the Docker image.
There were no major updates that added new functionality since the last release. Therefore I did not update the Docker image.
In the future I plan on updating the Docker image with every new regular release.

If you are interested, I could create a GitHub Action for automatically publishing nightly versions with every commit. However, it might be unstable and may not work correctly, since these versions will not be tested manually.

**Comment by er2de2** [comment]
I asked about the new version mainly because I was the one who did the Polish translation 😀  and I wanted to see how it worked out.
